### ISSUE TITLE
osl_strings_generate input - char * -> const char *

### ISSUE THREAD

**Issue by bondhugula** [periscop/openscop#39]
https://github.com/periscop/openscop/blob/39396a02cbfdad8c25accb425e1beefe856498de/source/strings.c#L476

Could these be changed to take 'const char *' instead of 'char *'? Otherwise, these lead to compiler warnings when being used from C++.

 warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   osl_strings_p newnames = osl_strings_generate("t", nb_scatt);

Similar changes will be needed for other API functions.

**Comment by harenome** [comment]
This should not occur anymore with the current master head.
