### ISSUE TITLE
compiler build warning

### ISSUE THREAD

**Issue by bondhugula** [periscop/openscop#41]
With GCC 8.3.1 and -Wextra, I see the following warning with the current master tip 39396a02cbfdad8c25accb425e1beefe856498de

source/relation.c: In function ‘osl_relation_interface’:
source/relation.c:3010:23: warning: cast between incompatible function types from ‘struct osl_relation * (*)(int,  int)’ to ‘void * (*)(void)’ [-Wcast-function-type]
   interface->malloc = (osl_malloc_f)osl_relation_malloc;
                       ^
  CC       source/libosl_la-vector.lo

**Comment by bondhugula** [comment]
Is this going to be committed soon? Thanks.

**Comment by harenome** [comment]
This should not occur anymore with the current master head.
